change mocha by jest

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -36,8 +36,6 @@ jobs:
       fail-fast: false
       matrix:
         os:
-          - ubuntu-18.04
-          - ubuntu-20.04
           - ubuntu-22.04
           - macos-latest
           - windows-latest
@@ -59,7 +57,7 @@ jobs:
         if: always()
         with:
           name: test-report-html-${{ matrix.os }}
-          path: mochawesome-report
+          path: test-report
 
   ##############################################################################
   # Documentation
@@ -93,18 +91,6 @@ jobs:
         uses: actions/checkout@v3
       - name: Install modules
         run: npm install
-      # ubuntu 18.04
-      - name: Download artifacts Ubuntu 18.04
-        uses: actions/download-artifact@v3
-        with:
-          name: test-report-html-ubuntu-18.04
-          path: test-report-html-ubuntu-18.04
-      # ubuntu 20.04
-      - name: Download artifacts Ubuntu 20.04
-        uses: actions/download-artifact@v3
-        with:
-          name: test-report-html-ubuntu-20.04
-          path: test-report-html-ubuntu-20.04
       # ubuntu 22.04
       - name: Download artifacts Ubuntu 22.04
         uses: actions/download-artifact@v3
@@ -131,8 +117,6 @@ jobs:
           path: api-doc
       - name: Rename directories
         run: |
-          mv test-report-html-ubuntu-18.04 docs
-          mv test-report-html-ubuntu-20.04 docs
           mv test-report-html-ubuntu-22.04 docs
           mv test-report-html-macos-latest docs
           mv test-report-html-windows-latest docs
@@ -165,87 +149,87 @@ jobs:
           branch: gh-pages
           folder: doc-web
 
-  ##############################################################################
-  # Command line pack
-  ##############################################################################
-  command-line-teroshdl-pack:
-    needs: [unit-test]
-    name: Pack TerosHDL
-    runs-on: ubuntu-20.04
-    container: ubuntu:20.04
-    steps:
-      - run: apt update
-      - run: apt install -y nsis p7zip-full p7zip-rar git curl tar xz-utils apt-utils
-      - run: git config --global --add safe.directory /__w/colibri/colibri
-      - uses: actions/setup-node@v2
-        with:
-          node-version: "16"
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Install modules
-        run: npm install
-      - name: Compile
-        run: npm run compile
-      - run: npm install oclif
-      - run: npx oclif pack tarballs -r . --parallel
-      - name: Save pack
-        uses: actions/upload-artifact@v3
-        with:
-          name: teroshdl-pack
-          path: dist
+  # ##############################################################################
+  # # Command line pack
+  # ##############################################################################
+  # command-line-teroshdl-pack:
+  #   needs: [unit-test]
+  #   name: Pack TerosHDL
+  #   runs-on: ubuntu-20.04
+  #   container: ubuntu:20.04
+  #   steps:
+  #     - run: apt update
+  #     - run: apt install -y nsis p7zip-full p7zip-rar git curl tar xz-utils apt-utils
+  #     - run: git config --global --add safe.directory /__w/colibri/colibri
+  #     - uses: actions/setup-node@v2
+  #       with:
+  #         node-version: "16"
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
+  #     - name: Install modules
+  #       run: npm install
+  #     - name: Compile
+  #       run: npm run compile
+  #     - run: npm install oclif
+  #     - run: npx oclif pack tarballs -r . --parallel
+  #     - name: Save pack
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: teroshdl-pack
+  #         path: dist
 
-  ##############################################################################
-  # Publish package
-  ##############################################################################
-  publish-release:
-    if: github.ref == 'refs/heads/main'
-    runs-on: ubuntu-latest
-    needs: [command-line-teroshdl-pack]
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Set node enviroment
-        uses: actions/setup-node@v3
-        with:
-          node-version: 12
-      - name: npm install
-        run: |
-          npm install
-      - name: Compile
-        run: |
-          npm run compile
-      - name: Publish NPM package
-        id: publish
-        uses: JS-DevTools/npm-publish@v1
-        with:
-          token: ${{ secrets.NPM_TOKEN }}
-          check-version: true
-      - name: Package not published
-        if: steps.publish.outputs.type == '' || steps.publish.outputs.type == 'none'
-        run: |
-          echo "Error, version not changed."
-          exit 1
-      - name: Tar for release
-        run: |
-          cd ..
-          tar -cvzf teroshdl2-${{ steps.publish.outputs.version }}.tar.gz colibri
-          mv teroshdl2-${{ steps.publish.outputs.version }}.tar.gz colibri
-          cd colibri
+  # ##############################################################################
+  # # Publish package
+  # ##############################################################################
+  # publish-release:
+  #   if: github.ref == 'refs/heads/main'
+  #   runs-on: ubuntu-latest
+  #   needs: [command-line-teroshdl-pack]
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v3
+  #     - name: Set node enviroment
+  #       uses: actions/setup-node@v3
+  #       with:
+  #         node-version: 12
+  #     - name: npm install
+  #       run: |
+  #         npm install
+  #     - name: Compile
+  #       run: |
+  #         npm run compile
+  #     - name: Publish NPM package
+  #       id: publish
+  #       uses: JS-DevTools/npm-publish@v1
+  #       with:
+  #         token: ${{ secrets.NPM_TOKEN }}
+  #         check-version: true
+  #     - name: Package not published
+  #       if: steps.publish.outputs.type == '' || steps.publish.outputs.type == 'none'
+  #       run: |
+  #         echo "Error, version not changed."
+  #         exit 1
+  #     - name: Tar for release
+  #       run: |
+  #         cd ..
+  #         tar -cvzf teroshdl2-${{ steps.publish.outputs.version }}.tar.gz colibri
+  #         mv teroshdl2-${{ steps.publish.outputs.version }}.tar.gz colibri
+  #         cd colibri
 
-      - name: Download artifacts pack
-        uses: actions/download-artifact@v3
-        with:
-          name: teroshdl-pack
-          path: teroshdl-pack
+  #     - name: Download artifacts pack
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: teroshdl-pack
+  #         path: teroshdl-pack
 
-      - name: Create release
-        uses: "marvinpinto/action-automatic-releases@latest"
-        with:
-          repo_token: "${{ secrets.GITHUB_TOKEN }}"
-          automatic_release_tag: ${{ steps.publish.outputs.version }}
-          prerelease: false
-          files: |
-            ./teroshdl-pack/*.tar.gz
-      - name: Released
-        run: |
-          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
+  #     - name: Create release
+  #       uses: "marvinpinto/action-automatic-releases@latest"
+  #       with:
+  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
+  #         automatic_release_tag: ${{ steps.publish.outputs.version }}
+  #         prerelease: false
+  #         files: |
+  #           ./teroshdl-pack/*.tar.gz
+  #     - name: Released
+  #       run: |
+  #         echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
